### ISSUE TITLE
Go hands on tutorial

### ISSUE THREAD

**Issue by vishal-biyani** [infracloudio/citadel#16]
Include the hands on Go tutorial which introduces GRPC etc. in a very structured manner: https://ewanvalentine.io/microservices-in-golang-part-1/

**Comment by anubhav6663** [comment]
This tutorial is already included under microservices assignments. 

https://dzone.com/articles/create-versatile-microservices-in-golang-part-1

**Comment by sanketsudake** [comment]
Closing this as per Anubhav's comment. We already have similar tutorial in repo.
